// ─── Real Evidence Seeder ──────────────────────────────────────────────────────
//
// Adds genuine peer-reviewed research documents to the library.
// Every document here corresponds to a real published source.
// No fabricated authors, journals, abstracts, or DOIs.
//
// Governance:
//   1. createResearchDocument (status=pending, isActive=false)
//   2. analyzeResearchDocument (Librarian Agent evaluation)
//   3. Status applied automatically based on recommendation
//      approve      → status=approved, isActive=true
//      needs_review → status=pending,  isActive=false (admin confirms)
//      reject       → status=rejected, isActive=false
//
// Run:
//   pnpm --filter @workspace/api-server exec tsx --tsconfig tsconfig.json \
//     src/scripts/run-real-evidence-seeder.ts

import type { InsertResearchDocument } from "@workspace/db";

// ─── Document catalog ─────────────────────────────────────────────────────────

export const REAL_EVIDENCE_DOCUMENTS: Omit<InsertResearchDocument, "status" | "isActive">[] = [

  // ── HYPERTROPHY ──────────────────────────────────────────────────────────────

  {
    title: "Dose-Response Relationship Between Weekly Resistance Training Volume and Increases in Muscle Mass: A Systematic Review and Meta-Analysis",
    authors: "Schoenfeld BJ, Ogborn D, Krieger JW",
    year: 2017,
    source: "Journal of Strength and Conditioning Research",
    journal: "Journal of Strength and Conditioning Research",
    doi: "10.1519/JSC.0000000000001974",
    category: "strength_conditioning",
    evidenceType: "systematic_review",
    trustLevel: "gold",
    confidence: "strong",
    topicTags: ["hypertrophy", "volume", "muscle_growth", "training_frequency", "rep_ranges"],
    populationTags: ["trained_adults", "general_population"],
    abstract:
      "This systematic review and meta-analysis examined the dose-response relationship between weekly resistance training volume (sets per muscle group) and muscle hypertrophy in trained individuals. A significant dose-response relationship was found: higher weekly volumes (>10 sets/muscle group/week) produced greater hypertrophy than lower volumes (<5 sets/week). Moderate volumes (5–9 sets/week) produced intermediate gains. No significant advantage was found for very high volumes (20+ sets/week) in trained subjects over moderate-to-high volumes, suggesting a practical upper limit. The review included 15 studies meeting inclusion criteria.",
    coachingImplications:
      "For hypertrophy goals, progressive volume increase is the primary driver. Start at 10–12 sets per muscle group per week for trained individuals. Well-trained athletes may benefit from 15–20 sets per week for lagging muscle groups. Volume should be accumulated across multiple sessions rather than a single session to manage fatigue.",
    programmingImplications:
      "Distribute weekly volume across 2–3 sessions per muscle group. Use 3–5 sets per exercise, 3–4 exercises per muscle group. Progress volume by adding sets before adding load. Weekly set targets: 10 sets = minimum effective dose; 15+ sets = higher-end hypertrophy stimulus. Deload every 4–6 weeks to manage accumulated fatigue.",
    safetyConsiderations:
      "Higher volumes require adequate recovery. Very high volumes (20+ sets/week) without progressive acclimation increase injury risk. Monitor joint and connective tissue response when rapidly increasing volume.",
    limitations:
      "Most included studies used untrained or recreationally trained subjects. Optimal volume for advanced trainees may differ. Individual response variation is high.",
    contraindications:
      "High weekly volumes (15+ sets per muscle group) are inappropriate for beginners or those returning from injury without progressive build-up.",
  },

  {
    title: "The Mechanisms of Muscle Hypertrophy and Their Application to Resistance Training",
    authors: "Schoenfeld BJ",
    year: 2010,
    source: "Journal of Strength and Conditioning Research",
    journal: "Journal of Strength and Conditioning Research",
    doi: "10.1519/JSC.0b013e3181e840f3",
    category: "strength_conditioning",
    evidenceType: "review",
    trustLevel: "high",
    confidence: "strong",
    topicTags: ["hypertrophy", "muscle_growth", "rep_ranges", "progressive_overload", "exercise_selection"],
    populationTags: ["trained_adults", "general_population"],
    abstract:
      "This review synthesizes the mechanistic bases of skeletal muscle hypertrophy in response to resistance training. Three primary mechanisms are identified: mechanical tension (the primary driver), metabolic stress (the 'pump' stimulus), and muscle damage (secondary mechanism). Mechanical tension generated by heavy, controlled loading is the dominant signal for protein synthesis and satellite cell activation. Metabolic stress from moderate loads with high repetitions contributes to hypertrophy via cell swelling, hypoxia, and hormone release. Muscle damage, while stimulating remodeling, may not be a prerequisite for hypertrophy. Practical applications for training program design are discussed.",
    coachingImplications:
      "Prioritize mechanical tension: load in the 6–12 rep range (67–85% 1RM) is the classic hypertrophy zone, but evidence shows muscle can grow across rep ranges (5–30 reps) if sets are taken close to failure. The 'pump' (metabolic stress) contributes to growth but should not replace heavy work. Progressive overload — adding weight, reps, or sets over time — is essential.",
    programmingImplications:
      "Include compound movements at 6–12 reps (primary stimulus) and isolation work at 12–20 reps (metabolic stress supplement). Take working sets within 1–3 reps of failure for optimal stimulus. Vary rep ranges across a training block to stimulate multiple hypertrophy mechanisms. Avoid excessive muscle damage (extreme soreness) that impairs training frequency.",
    safetyConsiderations:
      "Training close to failure with heavy loads requires proper technique. Excessive muscle damage from novel exercises or extreme eccentrics can impair recovery for 5–7 days.",
    limitations:
      "Mechanistic research often uses isolated models or extreme conditions not fully replicable in practical training. Individual variation in hypertrophic response is substantial.",
    contraindications: null,
  },

  // ── KNEE PAIN / RETURN TO TRAINING ───────────────────────────────────────────

  {
    title: "Evidence-Based Clinical Practice Update: Practice Guidelines for Anterior Cruciate Ligament Rehabilitation Based on a Systematic Review and Multidisciplinary Consensus",
    authors: "van Melick N, van Cingel RE, Brooijmans F, Neeter C, van Tienen T, Hullegie W, Nijhuis-van der Sanden MW",
    year: 2016,
    source: "British Journal of Sports Medicine",
    journal: "British Journal of Sports Medicine",
    doi: "10.1136/bjsports-2015-095898",
    category: "medical_rehab",
    evidenceType: "systematic_review",
    trustLevel: "gold",
    confidence: "strong",
    topicTags: ["knee", "return_to_training", "rehab", "pain_modification", "strength_training"],
    populationTags: ["post_surgical", "athletes", "active_adults"],
    abstract:
      "This multidisciplinary consensus statement provides evidence-based practice guidelines for ACL rehabilitation and return-to-sport decision-making. Key findings: return-to-sport criteria should include limb symmetry index (LSI) of ≥90% for quadriceps and hamstring strength, functional performance tests (hop tests), and psychological readiness. Time-based criteria alone are insufficient. Criteria-based progression outperforms calendar-based protocols. Neuromuscular training — including balance, proprioception, and sport-specific movement — is essential from early rehabilitation stages. High re-injury rates (15–25%) in the first year of return to cutting sports are partly attributable to premature clearance.",
    coachingImplications:
      "For clients returning from ACL surgery or serious knee injury: do not rely on time (e.g., '6 months post-op') as the sole clearance criterion. Strength symmetry between limbs (≥90% LSI) and passing hop tests are evidence-based gates. Work with the athlete's physiotherapist on clearance criteria. Proprioceptive and neuromuscular work must precede return to cutting and change-of-direction training.",
    programmingImplications:
      "Return-to-training programming phases: Phase 1 — restore ROM and neuromuscular control (bodyweight, isometric); Phase 2 — strength rebuilding (bilateral then unilateral loaded exercises, LSI target ≥80%); Phase 3 — power and speed (plyometrics, acceleration, change of direction); Phase 4 — sport-specific (return to full training when LSI ≥90% and hop tests passed). Never skip or abbreviate phases based on perceived fitness.",
    safetyConsiderations:
      "ACL re-injury risk is highest in the first year post-surgery. Do not programme high-load cutting, reactive agility, or contact drills until criteria-based clearance is achieved. Consult with the treating physiotherapist or sports medicine physician before designing return-to-sport programming.",
    limitations:
      "Most ACL research focuses on surgical cases. Non-surgical ACL management (conservative) has less robust evidence for return-to-sport criteria. Individual surgeon protocols vary.",
    contraindications:
      "Plyometrics, agility drills, and high-speed cutting are contraindicated until Phase 3 criteria are met. Do not begin strength-based ACL programming without physiotherapy clearance.",
  },

  {
    title: "Simple Decision Rules Can Reduce Reinjury Risk by 84% After ACL Reconstruction: The Delaware-Oslo ACL Cohort Study",
    authors: "Grindem H, Snyder-Mackler L, Moksnes H, Engebretsen L, Risberg MA",
    year: 2016,
    source: "British Journal of Sports Medicine",
    journal: "British Journal of Sports Medicine",
    doi: "10.1136/bjsports-2016-096031",
    category: "medical_rehab",
    evidenceType: "prospective_study",
    trustLevel: "gold",
    confidence: "strong",
    topicTags: ["knee", "return_to_training", "rehab", "pain_modification", "strength_training", "sport_performance"],
    populationTags: ["post_surgical", "athletes"],
    abstract:
      "The Delaware-Oslo ACL cohort study (n=107 athletes) found that athletes who met three criteria before returning to sport had an 84% lower reinjury rate than those who did not: (1) ≥9 months post-surgery, (2) quadriceps strength symmetry ≥90% LSI, and (3) passing a 4-hop test battery at ≥90% LSI. Athletes clearing all three criteria had a 5% reinjury rate versus 38% in those who met none. This study provides the strongest available evidence for criteria-based return-to-sport decision-making after ACL reconstruction.",
    coachingImplications:
      "The three criteria from this study are among the best-validated decision rules available for post-ACL return to sport: (1) 9+ months post-surgery, (2) quad strength symmetry ≥90%, (3) hop test symmetry ≥90%. If a client has not met all three, the reinjury risk is substantially elevated and high-load, high-speed sport training should not be prescribed.",
    programmingImplications:
      "Use LSI-based milestones to gate training phase progression. Quad strength testing (isokinetic dynamometer or estimated via single-leg leg press) at regular intervals. Single-leg hop, triple hop, and 6-metre timed hop are practical field-based assessments. Programme the final 1–2 months before return to full sport as sport-specific high-velocity work only after all three gates are passed.",
    safetyConsiderations:
      "Calendar-based clearance (e.g., 'cleared at 6 months') is associated with 3–8× higher reinjury rates than criteria-based clearance. Always integrate time + strength + function criteria together.",
    limitations:
      "Sample was primarily young athletes in cutting/pivoting sports. May not fully generalize to recreational athletes or non-surgical ACL management.",
    contraindications: null,
  },

  // ── TENDON / OVERUSE ─────────────────────────────────────────────────────────

  {
    title: "Is Tendon Pathology a Continuum? A Pathology Model to Explain the Clinical Presentation of Load-Induced Tendinopathy",
    authors: "Cook JL, Purdam CR",
    year: 2009,
    source: "British Journal of Sports Medicine",
    journal: "British Journal of Sports Medicine",
    doi: "10.1136/bjsm.2008.051193",
    category: "medical_rehab",
    evidenceType: "review",
    trustLevel: "gold",
    confidence: "strong",
    topicTags: ["tendon", "pain_modification", "return_to_training", "rehab", "load_management"],
    populationTags: ["athletes", "active_adults", "older_adult"],
    abstract:
      "This landmark paper proposes the tendon continuum model: a three-stage progression from reactive tendinopathy (acute overload response), to tendon dysrepair (failed healing), to degenerative tendinopathy (irreversible structural change). Each stage requires different management. Reactive tendinopathy responds best to load reduction and isometric exercises. Tendon dysrepair requires progressive isotonic loading. Degenerative tendinopathy may not reverse structural changes but symptoms and function can be substantially improved with exercise. The model explains why aggressive stretching, passive treatments, and absolute rest worsen tendinopathy, while carefully dosed progressive load improves it.",
    coachingImplications:
      "Never prescribe complete rest for tendinopathy — deloading (not zero load) and progressive reloading are the evidence-based approach. Heavy stretching of a reactive tendon compresses the tendinopathic zone and worsens pain. Identify the stage before prescribing load: acute presentation (reactive) → reduce load and add isometrics; chronic (degenerative) → progressive isotonic heavy-slow resistance. Tendons need load — the question is how much and how fast to progress.",
    programmingImplications:
      "Reactive tendinopathy: reduce provocative load (e.g., cut plyometric volume by 50%), add isometric holds at 70% effort (45 sec × 5 reps, twice daily). Tendon dysrepair and degenerative: heavy-slow resistance (HSR) protocol — 3–4 sets × 6–8 reps, 3× per week, 12–16 week progression. Plyometrics and high-speed loading reintroduced only after pain-free HSR at full load. Progress load every 2 weeks guided by 24-hour symptom response.",
    safetyConsiderations:
      "Provocative load testing: if pain exceeds 5/10 during or rises post-exercise (24-hour rule), the load was too high. Monitor morning stiffness — a reliable indicator of tendon irritation. Do not ignore asymptomatic tendinopathy in athletes; reactive tendon is vulnerable to catastrophic failure under sudden overload.",
    limitations:
      "Model is a clinical framework, not a confirmed histological staging tool. Biopsy studies show structural overlap between stages. Not all tendinopathies follow the continuum linearly.",
    contraindications:
      "Aggressive stretching into end-range dorsiflexion or knee flexion is contraindicated for Achilles and patellar tendinopathy respectively in reactive/dysrepair stages. High-speed, high-load plyometrics are contraindicated until the reactive phase has resolved.",
  },

  {
    title: "Isometric Exercise Induces Analgesia and Reduces Inhibition in Patellar Tendinopathy",
    authors: "Rio E, Kidgell D, Purdam C, Gaida J, Moseley GL, Pearce AJ, Cook J",
    year: 2015,
    source: "British Journal of Sports Medicine",
    journal: "British Journal of Sports Medicine",
    doi: "10.1136/bjsports-2014-094386",
    category: "medical_rehab",
    evidenceType: "rct",
    trustLevel: "gold",
    confidence: "moderate",
    topicTags: ["tendon", "pain_modification", "rehab", "knee"],
    populationTags: ["athletes", "active_adults"],
    abstract:
      "This RCT compared isometric versus isotonic quadriceps exercise in athletes with patellar tendinopathy during in-season sport participation. Isometric quadriceps contractions at 70% MVIC held for 45 seconds immediately reduced pain scores by 40–50% (on VAS), with analgesia lasting up to 45 minutes post-exercise. Isotonic exercise did not produce comparable immediate analgesia. Isometric exercise also reduced cortical inhibition of the quadriceps (assessed via transcranial magnetic stimulation), suggesting a neurological mechanism beyond simple fatigue or distraction. The protocol used: 5 × 45-second holds at 70% MVIC in a wall-sit or leg press position, performed daily.",
    coachingImplications:
      "Isometric holds are a first-line tool for managing patellar (and Achilles) tendon pain during in-season or competitive periods when complete rest is not feasible. The 5 × 45-second protocol provides real pain relief and can be performed pre-training to reduce pain during activity. This does not replace progressive loading — it is a pain management adjunct during the reactive or dysrepair phase.",
    programmingImplications:
      "Isometric protocol: wall-sit or leg press at 60–70° knee flexion, 5 sets × 45 seconds, daily. Combine with heavy-slow resistance training (isotonic) 3× per week for longer-term structural adaptation. The isometric protocol is suitable for in-season management; move to full isotonic HSR loading during the off-season.",
    safetyConsiderations:
      "Isometric loads at 70% MVIC are generally safe for reactive tendinopathy. Avoid angles that produce compressive tendon loading (deep flexion >90° for patellar, plantar-flexion with weight for Achilles). If pain during isometrics exceeds 5/10, reduce load or angle.",
    limitations:
      "Small sample (n=6 per group). Short follow-up (immediately post-exercise and 45 minutes). Mechanism (cortical inhibition reduction) requires replication in larger samples. May not generalize to Achilles tendinopathy without further specific study.",
    contraindications: null,
  },

  // ── ACCELERATION / SPEED ─────────────────────────────────────────────────────

  {
    title: "Sprint Running Performance Monitoring: Methodological and Practical Considerations",
    authors: "Haugen T, Buchheit M",
    year: 2016,
    source: "Sports Medicine",
    journal: "Sports Medicine",
    doi: "10.1007/s40279-015-0446-0",
    category: "sport_performance",
    evidenceType: "review",
    trustLevel: "high",
    confidence: "strong",
    topicTags: ["speed", "sprint_mechanics", "acceleration", "athletic_performance", "sport_performance"],
    populationTags: ["athletes", "team_sport_athletes"],
    abstract:
      "This review examines the scientific basis of sprint performance monitoring and training, covering the phases of sprint running (acceleration, maximum velocity, velocity maintenance), determinants of performance at each phase, and practical monitoring methods. Key findings: acceleration (0–30m) is primarily force-application dependent (horizontal force vector); maximum velocity requires reactive strength and high swing leg mechanics; these phases require different training emphases. Sprint training frequency of 2–3 sessions per week with appropriate recovery is supported. Volume: 300–600m of sprint volume per session is appropriate for team sport athletes, with warm-up comprising movement preparation and low-intensity acceleration runs before maximum velocity work.",
    coachingImplications:
      "Sprinting has two distinct training targets that require different exercises: (1) acceleration (0–10m) — driven by horizontal force application, improved by resisted sprinting, sled pulls, and strength-power training; (2) maximum velocity (30m+) — driven by reactive strength and high stride frequency, improved by wicket runs, A/B drills, and flying sprints. Most team sport athletes need more acceleration training than max velocity work. Pure speed work requires full neural recovery — 90–120 seconds between efforts minimum.",
    programmingImplications:
      "Sprint session structure: 15–20 minute movement preparation → low-intensity acceleration runs (50–70% effort) → top-speed work or acceleration work (2–4 reps × 10–40m, full recovery). Total weekly sprint volume 600–1200m for team sport athletes. Place sprint sessions at the start of the week or early in the microcycle before fatigue accumulates. Never follow a sprint session with high-volume lower body strength training on the same day.",
    safetyConsiderations:
      "Hamstring strain risk is highest in the maximum velocity phase. Ensure proper movement preparation including hip flexor activation, glute activation, and A-drill mechanics before max-speed work. Avoid maximal sprinting when fatigued — gradual build-up to top speed is essential. Return to sprint work after lower-body injury must be progression-based (submaximal before maximal).",
    limitations:
      "Much sprint research uses elite athletes; application to recreational athletes requires adjustment. Field-based timing systems have variable accuracy. Sprint biomechanics research often uses controlled laboratory conditions.",
    contraindications:
      "Maximal-intensity sprinting is contraindicated without adequate warm-up. Near-maximal sprint work (>90% effort) should not be programmed following heavy lower-body strength training in the same session.",
  },

  {
    title: "Interpreting Power-Force-Velocity Profiles for Individualized and Specific Training",
    authors: "Morin JB, Samozino P",
    year: 2016,
    source: "International Journal of Sports Physiology and Performance",
    journal: "International Journal of Sports Physiology and Performance",
    doi: "10.1123/ijspp.2015-0638",
    category: "sport_performance",
    evidenceType: "review",
    trustLevel: "high",
    confidence: "moderate",
    topicTags: ["speed", "force_velocity", "acceleration", "strength_training", "athletic_performance", "power_development"],
    populationTags: ["athletes", "team_sport_athletes"],
    abstract:
      "The force-velocity (F-V) profile describes the individual relationship between force production and velocity of movement, and predicts sprint mechanical qualities and athletic power output. Athletes can be force-deficient (high velocity, low force — common in untrained or endurance athletes) or velocity-deficient (high force, low velocity — common in strength-trained athletes). Individualizing training to target the deficient end of the F-V spectrum produces larger performance gains than non-individualized programming. Practical assessment from sprint split-times or jump testing allows F-V profiling without laboratory equipment.",
    coachingImplications:
      "One program does not fit all for speed development. A strength-trained athlete who is already 'force-sufficient' will gain more speed from plyometric and light resisted training (velocity side) than from more heavy lifting. A weak or untrained athlete needs to develop the force side first. Assessing whether a client is force- or velocity-deficient guides where to invest training time for maximal speed improvement.",
    programmingImplications:
      "Force-deficient profile: prioritize heavy resistance training (squats, deadlifts, hip thrusts), weighted sled sprints (loading at 80–120% body mass). Velocity-deficient profile: prioritize plyometrics, light resisted sprints (10–20% body mass sled), unresisted acceleration and max velocity work. Balanced profiles: standard sprint and strength programming. Re-assess every 8–12 weeks to track profile shift.",
    safetyConsiderations:
      "Heavy sled loading (>80% BM) places high demands on hip flexors and lumbar spine. Ensure adequate hip flexor mobility and core control before heavy resisted sprint work.",
    limitations:
      "F-V profiling from field sprints has measurement limitations; laboratory dynamometry is more precise. Training to shift the profile requires sufficient volume — effects may take 8+ weeks to manifest. Profile interpretation in team sports is complicated by positional demands.",
    contraindications: null,
  },

  // ── CONDITIONING / ENERGY SYSTEMS ────────────────────────────────────────────

  {
    title: "High-Intensity Interval Training, Solutions to the Programming Puzzle. Part I: Cardiopulmonary Emphasis",
    authors: "Buchheit M, Laursen PB",
    year: 2013,
    source: "Sports Medicine",
    journal: "Sports Medicine",
    doi: "10.1007/s40279-013-0029-x",
    category: "sport_performance",
    evidenceType: "review",
    trustLevel: "gold",
    confidence: "strong",
    topicTags: ["conditioning", "endurance", "energy_systems", "hiit", "sport_performance", "concurrent_training"],
    populationTags: ["athletes", "active_adults", "team_sport_athletes"],
    abstract:
      "This comprehensive review addresses the programming variables of high-intensity interval training (HIIT) for cardiopulmonary adaptation. Key determinants examined: work interval intensity (% VO2max or % HRmax), work interval duration (10 seconds to 4–8 minutes), recovery interval duration and intensity, and number of repetitions and series. Longer work intervals (3–8 min at 90–95% HRmax) produce the greatest VO2max improvements; shorter intervals (10–30 seconds at >95% HRmax) develop speed endurance and repeated sprint ability. Training status mediates response: untrained individuals respond to all HIIT formats; trained athletes require higher intensities for continued adaptation. The review provides a practical framework for selecting work:rest ratios based on training goals.",
    coachingImplications:
      "HIIT is not monolithic — the format dramatically changes the adaptation. Long intervals (4 × 4 min at 90% HRmax, 3 min recovery) are the most researched and reliably improve VO2max. Short intervals (10-20s on/off, 15-30 at >100% vVO2max) develop repeated sprint ability. Match the HIIT format to the athlete's goal and sport. For strength-focused athletes, limit HIIT to 2 sessions per week to avoid interference with strength adaptation.",
    programmingImplications:
      "VO2max development: 4–6 × 4-minute intervals at 85–95% HRmax, 3-minute active recovery, 2× per week. Repeated sprint ability: 6–10 × 20-second intervals at >100% vVO2max or all-out, 20–40 seconds passive recovery, 2–3× per week. Speed endurance: 6–8 × 200–400m at 90–95% max speed, full recovery (3–5 min). Do not combine high-volume HIIT with high-volume sprint training in the same week without monitoring fatigue.",
    safetyConsiderations:
      "High-intensity interval training significantly elevates cardiac demand. For clients >35 years without recent cardiovascular assessment, or those with cardiovascular risk factors, medical clearance is recommended before beginning HIIT at maximal intensities. Gradual introduction (start at 80% intensity, progress over 4–6 weeks) reduces injury and dropout risk.",
    limitations:
      "Most studies are 6–12 weeks. Long-term adaptation and appropriate volume for sustained use require more research. Highly trained athletes plateau in VO2max gains and may require altered approaches. Recovery between HIIT sessions (48–72 hours) is under-studied in concurrent training contexts.",
    contraindications:
      "Maximal HIIT is contraindicated for individuals with unmanaged hypertension, recent cardiac events, or conditions where maximal cardiovascular stress is medically restricted.",
  },

  {
    title: "The Scientific Basis for High-Intensity Interval Training: Optimising Training Programmes and Maximising Performance in Highly Trained Endurance Athletes",
    authors: "Laursen PB, Jenkins DG",
    year: 2002,
    source: "Sports Medicine",
    journal: "Sports Medicine",
    doi: "10.2165/00007256-200232010-00003",
    category: "sport_performance",
    evidenceType: "review",
    trustLevel: "high",
    confidence: "strong",
    topicTags: ["conditioning", "endurance", "energy_systems", "hiit", "periodization", "sport_performance"],
    populationTags: ["athletes", "endurance_athletes"],
    abstract:
      "This foundational review synthesizes the physiological adaptations underpinning HIIT-induced performance gains in highly trained endurance athletes. HIIT stimulates central (cardiac output, stroke volume) and peripheral (skeletal muscle oxidative enzyme activity, capillary density, lactate threshold) adaptations that moderate-intensity continuous training cannot match at comparable volumes. The review identifies optimal intensity (95–100% VO2max or 90–95% HRmax), duration (3–8 minutes per interval), and training frequency (2–3 sessions per week). Tapering with reduced volume but maintained intensity is recommended before competition. The paper remains a foundational reference in endurance physiology.",
    coachingImplications:
      "For endurance-trained clients who have plateaued on moderate-intensity training, HIIT at near-maximal intensities (90–100% VO2max) is the primary tool for further performance gains. The key variable is intensity, not volume — reducing volume while maintaining intensity in the final 2 weeks before competition (taper) preserves fitness while recovering freshness. HIIT above lactate threshold is essential for highly trained individuals.",
    programmingImplications:
      "Foundation phase: build aerobic base with moderate-intensity work (70–80% HRmax) for 8–12 weeks. Specific preparation: introduce 2× weekly HIIT (3–6 × 3–5 min at 90–95% HRmax, 3–4 min recovery). Competition phase: maintain 1–2 HIIT sessions per week, reduce volume by 40–60%. Taper: reduce weekly training volume 40–60% over 2 weeks while maintaining at least 1 high-intensity session.",
    safetyConsiderations:
      "Highly trained athletes tolerate higher HIIT volumes; recreational athletes require longer base-building and gradual HIIT introduction. Overtraining risk is present when HIIT volume exceeds 2–3 sessions per week without adequate lower-intensity recovery.",
    limitations:
      "Focus on highly trained endurance athletes — findings may not apply to untrained populations without modification. The 2002 publication predates some refinements in HIIT research (e.g., polarized training model). Sport-mode specificity (running vs. cycling) affects exact adaptations.",
    contraindications:
      "HIIT at 95–100% VO2max is not appropriate for untrained individuals without progressive conditioning. Medical clearance required for individuals with cardiovascular risk factors.",
  },
];

// ─── Seeder logic ─────────────────────────────────────────────────────────────
// (imported and called from run-real-evidence-seeder.ts)
