/**
 * TrainChat Exercise Library — Decision-Ready Movement System
 *
 * NOT a list of exercise names. A coaching decision engine.
 * Structured around 12 core movement buckets.
 * ~55 exercises, each with full swap logic, constraint metadata, and sport transfer tags.
 *
 * Run: pnpm --filter @workspace/api-server tsx scripts/seed-exercises.ts
 *
 * Philosophy: Depth over count. The smartest library, not the biggest.
 */

import { db } from "@workspace/db";
import { exerciseLibrary } from "@workspace/db/schema";
import { sql } from "drizzle-orm";

type ExInput = {
  name: string;
  movementPattern: string;
  bodyRegion?: string;
  role?: string;
  unilateral?: boolean;
  primaryMuscle: string;
  secondaryMuscles: string[];
  equipment: string[];
  difficultyLevel: "beginner" | "intermediate" | "advanced" | "elite";
  neuralDemand?: "low" | "moderate" | "high";
  timeCost?: "low" | "moderate" | "high";
  intentTags: string[];
  sportTransferTags?: string[];
  jointStressProfile: string[];
  tags?: string[];
  clusterId?: string;
  easierVariations: string[];
  harderVariations: string[];
  description: string;
};

const EXERCISES: ExInput[] = [

  // ═══════════════════════════════════════════════════════════════════════════
  // 1. LOWER BODY — KNEE DOMINANT
  // cluster: knee_bilateral | knee_unilateral
  // ═══════════════════════════════════════════════════════════════════════════

  {
    name: "Back Squat",
    movementPattern: "knee_dominant",
    bodyRegion: "lower_body",
    role: "primary_strength",
    primaryMuscle: "quads",
    secondaryMuscles: ["glutes", "hamstrings", "core", "upper back"],
    equipment: ["barbell"],
    difficultyLevel: "intermediate",
    neuralDemand: "high",
    timeCost: "moderate",
    intentTags: ["strength", "hypertrophy", "athletic"],
    sportTransferTags: ["lower_body_force", "acceleration", "stiffness"],
    jointStressProfile: ["knee_dominant", "spine_load"],
    tags: ["bilateral"],
    clusterId: "knee_bilateral",
    easierVariations: ["Goblet Squat", "Box Squat"],
    harderVariations: ["Front Squat"],
    description: "Brace hard, bar on traps, controlled descent. Drive knees out on the way up. Primary bilateral knee-dominant strength option.",
  },

  {
    name: "Front Squat",
    movementPattern: "knee_dominant",
    bodyRegion: "lower_body",
    role: "primary_strength",
    primaryMuscle: "quads",
    secondaryMuscles: ["glutes", "core", "upper back"],
    equipment: ["barbell"],
    difficultyLevel: "advanced",
    neuralDemand: "high",
    timeCost: "moderate",
    intentTags: ["strength", "athletic", "hypertrophy"],
    sportTransferTags: ["lower_body_force", "trunk_stability"],
    jointStressProfile: ["knee_dominant", "wrist_stress", "spine_load"],
    tags: ["bilateral"],
    clusterId: "knee_bilateral",
    easierVariations: ["Back Squat", "Goblet Squat"],
    harderVariations: [],
    description: "Elbows high throughout. Upper back tightness is non-negotiable. Greater quad bias and trunk demand than back squat.",
  },

  {
    name: "Goblet Squat",
    movementPattern: "knee_dominant",
    bodyRegion: "lower_body",
    role: "primary_strength",
    primaryMuscle: "quads",
    secondaryMuscles: ["glutes", "core"],
    equipment: ["dumbbell", "kettlebell"],
    difficultyLevel: "beginner",
    neuralDemand: "low",
    timeCost: "low",
    intentTags: ["hypertrophy", "athletic", "fat_loss"],
    sportTransferTags: ["lower_body_force"],
    jointStressProfile: ["knee_dominant"],
    tags: ["bilateral", "beginner_friendly", "time_efficient"],
    clusterId: "knee_bilateral",
    easierVariations: ["Bodyweight Squat"],
    harderVariations: ["Back Squat", "Front Squat"],
    description: "Weight acts as counterbalance, keeps torso upright. Excellent for learning squat mechanics. Spine-friendly. Works with minimal equipment.",
  },

  {
    name: "Bodyweight Squat",
    movementPattern: "knee_dominant",
    bodyRegion: "lower_body",
    role: "prep_activation",
    primaryMuscle: "quads",
    secondaryMuscles: ["glutes"],
    equipment: ["bodyweight"],
    difficultyLevel: "beginner",
    neuralDemand: "low",
    timeCost: "low",
    intentTags: ["mobility", "activation", "athletic"],
    sportTransferTags: ["lower_body_force"],
    jointStressProfile: ["knee_dominant"],
    tags: ["bilateral", "beginner_friendly", "bodyweight_only", "time_efficient", "removable_when_compressed"],
    clusterId: "knee_bilateral",
    easierVariations: [],
    harderVariations: ["Goblet Squat", "Back Squat"],
    description: "Movement patterning baseline. Use in warm-up, as a regression, or for beginner populations.",
  },

  {
    name: "Safety Bar Squat",
    movementPattern: "knee_dominant",
    bodyRegion: "lower_body",
    role: "primary_strength",
    primaryMuscle: "quads",
    secondaryMuscles: ["glutes", "core"],
    equipment: ["barbell"],
    difficultyLevel: "intermediate",
    neuralDemand: "high",
    timeCost: "moderate",
    intentTags: ["strength", "hypertrophy", "rehab"],
    sportTransferTags: ["lower_body_force", "trunk_stability"],
    jointStressProfile: ["knee_dominant", "spine_load"],
    tags: ["bilateral", "shoulder_sensitive"],
    clusterId: "knee_bilateral",
    easierVariations: ["Goblet Squat"],
    harderVariations: ["Back Squat"],
    description: "Upper back and shoulder stress reduced vs. back squat. Ideal for training around shoulder or wrist limitations. High-torso squat pattern.",
  },

  {
    name: "Box Squat",
    movementPattern: "knee_dominant",
    bodyRegion: "lower_body",
    role: "primary_strength",
    primaryMuscle: "quads",
    secondaryMuscles: ["glutes", "hamstrings"],
    equipment: ["barbell"],
    difficultyLevel: "intermediate",
    neuralDemand: "moderate",
    timeCost: "moderate",
    intentTags: ["strength", "athletic"],
    sportTransferTags: ["lower_body_force", "acceleration"],
    jointStressProfile: ["knee_dominant", "spine_load"],
    tags: ["bilateral"],
    clusterId: "knee_bilateral",
    easierVariations: ["Goblet Squat"],
    harderVariations: ["Back Squat"],
    description: "Pause and reset on box — no bounce. Breaks stretch-shortening cycle, builds concentric power. Good for teaching hip hinge in squat pattern.",
  },

  {
    name: "RFESS (Bulgarian Split Squat)",
    movementPattern: "knee_dominant",
    bodyRegion: "lower_body",
    role: "unilateral_strength",
    unilateral: true,
    primaryMuscle: "quads",
    secondaryMuscles: ["glutes", "hamstrings", "core"],
    equipment: ["dumbbell", "barbell", "bodyweight"],
    difficultyLevel: "intermediate",
    neuralDemand: "moderate",
    timeCost: "moderate",
    intentTags: ["hypertrophy", "athletic", "strength"],
    sportTransferTags: ["lower_body_force", "deceleration", "change_of_direction"],
    jointStressProfile: ["knee_dominant", "hip_dominant"],
    tags: ["unilateral", "athletic"],
    clusterId: "knee_unilateral",
    easierVariations: ["Reverse Lunge", "Step-Up"],
    harderVariations: [],
    description: "Rear foot elevated. High unilateral quad and glute demand. Front foot far enough forward for vertical shin. Exposes bilateral asymmetries.",
  },

  {
    name: "Reverse Lunge",
    movementPattern: "knee_dominant",
    bodyRegion: "lower_body",
    role: "unilateral_strength",
    unilateral: true,
    primaryMuscle: "quads",
    secondaryMuscles: ["glutes", "hamstrings"],
    equipment: ["dumbbell", "barbell", "bodyweight"],
    difficultyLevel: "beginner",
    neuralDemand: "low",
    timeCost: "low",
    intentTags: ["hypertrophy", "athletic", "fat_loss"],
    sportTransferTags: ["deceleration", "change_of_direction"],
    jointStressProfile: ["knee_dominant"],
    tags: ["unilateral", "beginner_friendly"],
    clusterId: "knee_unilateral",
    easierVariations: ["Step-Up"],
    harderVariations: ["RFESS (Bulgarian Split Squat)", "Walking Lunge"],
    description: "Step back, not forward. Less knee shear than forward lunge. More controlled deceleration pattern. Good regression from RFESS.",
  },

  {
    name: "Step-Up",
    movementPattern: "knee_dominant",
    bodyRegion: "lower_body",
    role: "unilateral_strength",
    unilateral: true,
    primaryMuscle: "quads",
    secondaryMuscles: ["glutes", "core"],
    equipment: ["dumbbell", "bodyweight"],
    difficultyLevel: "beginner",
    neuralDemand: "low",
    timeCost: "low",
    intentTags: ["athletic", "fat_loss", "hypertrophy"],
    sportTransferTags: ["lower_body_force", "deceleration"],
    jointStressProfile: ["knee_dominant"],
    tags: ["unilateral", "beginner_friendly"],
    clusterId: "knee_unilateral",
    easierVariations: [],
    harderVariations: ["Reverse Lunge", "RFESS (Bulgarian Split Squat)"],
    description: "Drive through the heel of the elevated leg. Single-leg strength without high skill demand. Good for older populations or injured athletes.",
  },

  {
    name: "Lateral Lunge",
    movementPattern: "knee_dominant",
    bodyRegion: "lower_body",
    role: "unilateral_strength",
    unilateral: true,
    primaryMuscle: "quads",
    secondaryMuscles: ["glutes", "adductors"],
    equipment: ["dumbbell", "bodyweight"],
    difficultyLevel: "beginner",
    neuralDemand: "low",
    timeCost: "low",
    intentTags: ["athletic", "mobility"],
    sportTransferTags: ["change_of_direction", "deceleration"],
    jointStressProfile: ["knee_dominant", "hip_dominant"],
    tags: ["unilateral", "athletic"],
    clusterId: "knee_unilateral",
    easierVariations: [],
    harderVariations: ["Cossack Squat"],
    description: "Side step into lateral squat. Critical for frontal-plane loading and adductor development. Underused in most programs. High sport transfer.",
  },

  {
    name: "Walking Lunge",
    movementPattern: "knee_dominant",
    bodyRegion: "lower_body",
    role: "unilateral_strength",
    unilateral: true,
    primaryMuscle: "quads",
    secondaryMuscles: ["glutes", "hamstrings", "core"],
    equipment: ["dumbbell", "barbell", "bodyweight"],
    difficultyLevel: "intermediate",
    neuralDemand: "moderate",
    timeCost: "moderate",
    intentTags: ["hypertrophy", "athletic", "fat_loss"],
    sportTransferTags: ["acceleration", "deceleration", "change_of_direction"],
    jointStressProfile: ["knee_dominant", "hip_dominant"],
    tags: ["unilateral", "athletic"],
    clusterId: "knee_unilateral",
    easierVariations: ["Reverse Lunge"],
    harderVariations: ["RFESS (Bulgarian Split Squat)"],
    description: "Alternating steps forward. High metabolic demand. Balance and coordination requirement. Excellent conditioning and athletic transfer combo.",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 2. LOWER BODY — HIP DOMINANT
  // cluster: hip_bilateral | hip_unilateral | hip_thrust_cluster
  // ═══════════════════════════════════════════════════════════════════════════

  {
    name: "Conventional Deadlift",
    movementPattern: "hip_dominant",
    bodyRegion: "lower_body",
    role: "primary_strength",
    primaryMuscle: "hamstrings",
    secondaryMuscles: ["glutes", "lower back", "core", "upper back"],
    equipment: ["barbell"],
    difficultyLevel: "intermediate",
    neuralDemand: "high",
    timeCost: "high",
    intentTags: ["strength", "athletic", "hypertrophy"],
    sportTransferTags: ["lower_body_force", "acceleration", "stiffness"],
    jointStressProfile: ["hip_dominant", "spine_load", "low_back_stress"],
    tags: ["bilateral"],
    clusterId: "hip_bilateral",
    easierVariations: ["Romanian Deadlift", "Trap Bar Deadlift"],
    harderVariations: [],
    description: "Bar over mid-foot, flat back, hips hinge to floor. Full posterior chain demand. High nervous system cost — program accordingly.",
  },

  {
    name: "Romanian Deadlift",
    movementPattern: "hip_dominant",
    bodyRegion: "lower_body",
    role: "primary_strength",
    primaryMuscle: "hamstrings",
    secondaryMuscles: ["glutes", "lower back"],
    equipment: ["barbell"],
    difficultyLevel: "intermediate",
    neuralDemand: "moderate",
    timeCost: "moderate",
    intentTags: ["strength", "hypertrophy", "athletic"],
    sportTransferTags: ["lower_body_force", "deceleration", "landing_control"],
    jointStressProfile: ["hip_dominant", "spine_load"],
    tags: ["bilateral"],
    clusterId: "hip_bilateral",
    easierVariations: ["Dumbbell RDL", "Hip Hinge Patterning Drill"],
    harderVariations: ["Conventional Deadlift"],
    description: "Bar stays close, hinge at hips, soft knee. Hamstring stretch at bottom is the training stimulus. Spine load lower than conventional.",
  },

  {
    name: "Trap Bar Deadlift",
    movementPattern: "hip_dominant",
    bodyRegion: "lower_body",
    role: "primary_strength",
    primaryMuscle: "glutes",
    secondaryMuscles: ["quads", "hamstrings", "core", "upper back"],
    equipment: ["trap_bar"],
    difficultyLevel: "intermediate",
    neuralDemand: "high",
    timeCost: "moderate",
    intentTags: ["strength", "athletic", "power"],
    sportTransferTags: ["lower_body_force", "acceleration", "stiffness"],
    jointStressProfile: ["hip_dominant", "knee_dominant"],
    tags: ["bilateral", "low_back_sensitive"],
    clusterId: "hip_bilateral",
    easierVariations: ["Romanian Deadlift", "Goblet Squat"],
    harderVariations: ["Conventional Deadlift"],
    description: "Handles at sides, neutral grip, more upright torso. Lower spinal shear than conventional. Often safer for power development and athletic populations.",
  },

  {
    name: "Dumbbell RDL",
    movementPattern: "hip_dominant",
    bodyRegion: "lower_body",
    role: "primary_strength",
    primaryMuscle: "hamstrings",
    secondaryMuscles: ["glutes", "lower back"],
    equipment: ["dumbbell"],
    difficultyLevel: "beginner",
    neuralDemand: "low",
    timeCost: "low",
    intentTags: ["hypertrophy", "athletic", "rehab"],
    sportTransferTags: ["lower_body_force", "landing_control"],
    jointStressProfile: ["hip_dominant"],
    tags: ["bilateral", "beginner_friendly", "time_efficient"],
    clusterId: "hip_bilateral",
    easierVariations: ["Hip Hinge Patterning Drill"],
    harderVariations: ["Romanian Deadlift"],
    description: "Dumbbells at sides or in front. Lower load demand on spine. Excellent progression into barbell RDL. Works well for home/travel.",
  },

  {
    name: "Hip Hinge Patterning Drill",
    movementPattern: "hip_dominant",
    bodyRegion: "lower_body",
    role: "prep_activation",
    primaryMuscle: "hamstrings",
    secondaryMuscles: ["glutes", "lower back"],
    equipment: ["bodyweight"],
    difficultyLevel: "beginner",
    neuralDemand: "low",
    timeCost: "low",
    intentTags: ["mobility", "activation", "rehab"],
    sportTransferTags: [],
    jointStressProfile: [],
    tags: ["beginner_friendly", "bodyweight_only", "time_efficient", "removable_when_compressed"],
    clusterId: "hip_bilateral",
    easierVariations: [],
    harderVariations: ["Dumbbell RDL", "Romanian Deadlift"],
    description: "Wall or dowel drill to groove hip hinge pattern. No load. Use for beginners, post-injury, or as session prep before heavy pulling.",
  },

  {
    name: "Single-Leg RDL",
    movementPattern: "hip_dominant",
    bodyRegion: "lower_body",
    role: "unilateral_strength",
    unilateral: true,
    primaryMuscle: "hamstrings",
    secondaryMuscles: ["glutes", "core"],
    equipment: ["dumbbell", "barbell", "bodyweight", "kettlebell"],
    difficultyLevel: "intermediate",
    neuralDemand: "moderate",
    timeCost: "moderate",
    intentTags: ["hypertrophy", "athletic", "rehab"],
    sportTransferTags: ["lower_body_force", "deceleration", "landing_control"],
    jointStressProfile: ["hip_dominant"],
    tags: ["unilateral", "athletic"],
    clusterId: "hip_unilateral",
    easierVariations: ["B-Stance RDL", "Dumbbell RDL"],
    harderVariations: [],
    description: "Hips square, free leg extends back, spine neutral. High demand on hip stability and hamstring strength. Critical for decel and landing mechanics.",
  },

  {
    name: "B-Stance RDL",
    movementPattern: "hip_dominant",
    bodyRegion: "lower_body",
    role: "unilateral_strength",
    unilateral: true,
    primaryMuscle: "hamstrings",
    secondaryMuscles: ["glutes", "core"],
    equipment: ["dumbbell", "barbell"],
    difficultyLevel: "beginner",
    neuralDemand: "low",
    timeCost: "low",
    intentTags: ["hypertrophy", "athletic"],
    sportTransferTags: ["lower_body_force", "landing_control"],
    jointStressProfile: ["hip_dominant"],
    tags: ["unilateral", "beginner_friendly"],
    clusterId: "hip_unilateral",
    easierVariations: ["Dumbbell RDL"],
    harderVariations: ["Single-Leg RDL"],
    description: "Rear toe touches for stability only — 80% load on front leg. Bridges the gap from bilateral to single-leg RDL. Lower balance demand.",
  },

  {
    name: "Hip Thrust",
    movementPattern: "hip_dominant",
    bodyRegion: "lower_body",
    role: "primary_strength",
    primaryMuscle: "glutes",
    secondaryMuscles: ["hamstrings", "core"],
    equipment: ["barbell", "dumbbell", "machine", "band"],
    difficultyLevel: "beginner",
    neuralDemand: "low",
    timeCost: "low",
    intentTags: ["hypertrophy", "strength", "athletic"],
    sportTransferTags: ["lower_body_force", "acceleration"],
    jointStressProfile: ["hip_dominant"],
    tags: ["bilateral", "low_back_sensitive", "beginner_friendly"],
    clusterId: "hip_bilateral",
    easierVariations: ["Glute Bridge"],
    harderVariations: ["Romanian Deadlift"],
    description: "Upper back on bench, bar over hips, drive through heels. Glute-dominant. Low spine load. Excellent complement to vertical hip hinge patterns.",
  },

  {
    name: "Glute Bridge",
    movementPattern: "hip_dominant",
    bodyRegion: "lower_body",
    role: "prep_activation",
    primaryMuscle: "glutes",
    secondaryMuscles: ["hamstrings", "core"],
    equipment: ["bodyweight", "band", "dumbbell"],
    difficultyLevel: "beginner",
    neuralDemand: "low",
    timeCost: "low",
    intentTags: ["activation", "rehab"],
    sportTransferTags: ["lower_body_force"],
    jointStressProfile: [],
    tags: ["bilateral", "beginner_friendly", "bodyweight_only", "removable_when_compressed"],
    clusterId: "hip_bilateral",
    easierVariations: [],
    harderVariations: ["Hip Thrust", "Single-Leg RDL"],
    description: "Supine position, feet flat, drive hips to ceiling. Use in warm-up to pre-activate glutes before lower body work.",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 3. UPPER PUSH — HORIZONTAL
  // cluster: push_horizontal
  // ═══════════════════════════════════════════════════════════════════════════

  {
    name: "Barbell Bench Press",
    movementPattern: "push_horizontal",
    bodyRegion: "upper_body",
    role: "primary_strength",
    primaryMuscle: "chest",
    secondaryMuscles: ["triceps", "anterior deltoid"],
    equipment: ["barbell"],
    difficultyLevel: "intermediate",
    neuralDemand: "moderate",
    timeCost: "moderate",
    intentTags: ["strength", "hypertrophy"],
    sportTransferTags: ["upper_body_force"],
    jointStressProfile: ["shoulder_dominant"],
    tags: ["bilateral"],
    clusterId: "push_horizontal",
    easierVariations: ["Dumbbell Bench Press", "Push-Up"],
    harderVariations: [],
    description: "Scapulae pinched and depressed, slight arch, bar to lower chest. Primary horizontal push strength exercise.",
  },

  {
    name: "Dumbbell Bench Press",
    movementPattern: "push_horizontal",
    bodyRegion: "upper_body",
    role: "primary_strength",
    primaryMuscle: "chest",
    secondaryMuscles: ["triceps", "anterior deltoid"],
    equipment: ["dumbbell"],
    difficultyLevel: "beginner",
    neuralDemand: "low",
    timeCost: "low",
    intentTags: ["hypertrophy", "strength"],
    sportTransferTags: ["upper_body_force"],
    jointStressProfile: ["shoulder_dominant"],
    tags: ["bilateral", "beginner_friendly"],
    clusterId: "push_horizontal",
    easierVariations: ["Push-Up"],
    harderVariations: ["Barbell Bench Press"],
    description: "Greater ROM than barbell. Each arm works independently. Good shoulder joint option when barbell irritates.",
  },

  {
    name: "Neutral Grip Dumbbell Press",
    movementPattern: "push_horizontal",
    bodyRegion: "upper_body",
    role: "primary_strength",
    primaryMuscle: "chest",
    secondaryMuscles: ["triceps", "anterior deltoid"],
    equipment: ["dumbbell"],
    difficultyLevel: "beginner",
    neuralDemand: "low",
    timeCost: "low",
    intentTags: ["hypertrophy", "rehab"],
    sportTransferTags: ["upper_body_force"],
    jointStressProfile: ["shoulder_dominant"],
    tags: ["bilateral", "shoulder_sensitive", "beginner_friendly"],
    clusterId: "push_horizontal",
    easierVariations: ["Push-Up"],
    harderVariations: ["Barbell Bench Press"],
    description: "Palms facing each other. Reduces shoulder impingement risk. Best horizontal press option for shoulder-sensitive athletes.",
  },

  {
    name: "Push-Up",
    movementPattern: "push_horizontal",
    bodyRegion: "upper_body",
    role: "primary_strength",
    primaryMuscle: "chest",
    secondaryMuscles: ["triceps", "core", "serratus"],
    equipment: ["bodyweight"],
    difficultyLevel: "beginner",
    neuralDemand: "low",
    timeCost: "low",
    intentTags: ["hypertrophy", "endurance", "athletic"],
    sportTransferTags: ["upper_body_force", "trunk_stability"],
    jointStressProfile: ["shoulder_dominant"],
    tags: ["bilateral", "beginner_friendly", "bodyweight_only", "time_efficient"],
    clusterId: "push_horizontal",
    easierVariations: [],
    harderVariations: ["Dumbbell Bench Press", "Barbell Bench Press"],
    description: "Scaps protract at top. Full core engagement throughout. Underrated for serratus development. Perfect regression or finisher.",
  },

  {
    name: "Incline Dumbbell Press",
    movementPattern: "push_horizontal",
    bodyRegion: "upper_body",
    role: "primary_strength",
    primaryMuscle: "chest",
    secondaryMuscles: ["anterior deltoid", "triceps"],
    equipment: ["dumbbell"],
    difficultyLevel: "beginner",
    neuralDemand: "low",
    timeCost: "moderate",
    intentTags: ["hypertrophy"],
    sportTransferTags: ["upper_body_force"],
    jointStressProfile: ["shoulder_dominant"],
    tags: ["bilateral", "beginner_friendly"],
    clusterId: "push_horizontal",
    easierVariations: ["Push-Up"],
    harderVariations: ["Barbell Bench Press"],
    description: "30–45° incline. Upper chest and shoulder emphasis. Reduced joint stress compared to flat barbell.",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 4. UPPER PUSH — VERTICAL
  // cluster: push_vertical
  // ═══════════════════════════════════════════════════════════════════════════

  {
    name: "Overhead Press",
    movementPattern: "push_vertical",
    bodyRegion: "upper_body",
    role: "primary_strength",
    primaryMuscle: "deltoids",
    secondaryMuscles: ["triceps", "upper traps", "core"],
    equipment: ["barbell"],
    difficultyLevel: "intermediate",
    neuralDemand: "moderate",
    timeCost: "moderate",
    intentTags: ["strength", "hypertrophy", "athletic"],
    sportTransferTags: ["upper_body_force", "trunk_stability"],
    jointStressProfile: ["shoulder_dominant", "spine_load"],
    tags: ["bilateral"],
    clusterId: "push_vertical",
    easierVariations: ["Dumbbell Shoulder Press", "Landmine Press"],
    harderVariations: [],
    description: "Bar starts at shoulders, press directly overhead. Requires thoracic extension. Full-body tension. Best vertical push strength builder.",
  },

  {
    name: "Dumbbell Shoulder Press",
    movementPattern: "push_vertical",
    bodyRegion: "upper_body",
    role: "primary_strength",
    primaryMuscle: "deltoids",
    secondaryMuscles: ["triceps", "upper traps"],
    equipment: ["dumbbell"],
    difficultyLevel: "beginner",
    neuralDemand: "low",
    timeCost: "low",
    intentTags: ["hypertrophy", "strength"],
    sportTransferTags: ["upper_body_force"],
    jointStressProfile: ["shoulder_dominant"],
    tags: ["bilateral", "beginner_friendly"],
    clusterId: "push_vertical",
    easierVariations: ["Landmine Press"],
    harderVariations: ["Overhead Press"],
    description: "Neutral or pronated grip. Lower demand than barbell OHP. Better ROM and shoulder joint path for most people.",
  },

  {
    name: "Landmine Press",
    movementPattern: "push_vertical",
    bodyRegion: "upper_body",
    role: "primary_strength",
    primaryMuscle: "deltoids",
    secondaryMuscles: ["chest", "triceps", "core"],
    equipment: ["barbell"],
    difficultyLevel: "beginner",
    neuralDemand: "low",
    timeCost: "low",
    intentTags: ["strength", "hypertrophy", "rehab"],
    sportTransferTags: ["upper_body_force", "rotational_power"],
    jointStressProfile: ["shoulder_dominant"],
    tags: ["bilateral", "shoulder_sensitive", "beginner_friendly"],
    clusterId: "push_vertical",
    easierVariations: [],
    harderVariations: ["Overhead Press"],
    description: "Diagonal pressing path — easier on shoulder joint. Use when barbell OHP causes pain. Great for athletic shoulder health.",
  },

  {
    name: "Half-Kneeling Press",
    movementPattern: "push_vertical",
    bodyRegion: "upper_body",
    role: "primary_strength",
    unilateral: true,
    primaryMuscle: "deltoids",
    secondaryMuscles: ["triceps", "core", "hip flexors"],
    equipment: ["dumbbell", "kettlebell", "cable"],
    difficultyLevel: "beginner",
    neuralDemand: "low",
    timeCost: "low",
    intentTags: ["strength", "hypertrophy", "athletic"],
    sportTransferTags: ["upper_body_force", "trunk_stability", "anti_rotation"],
    jointStressProfile: ["shoulder_dominant"],
    tags: ["unilateral", "beginner_friendly", "shoulder_sensitive"],
    clusterId: "push_vertical",
    easierVariations: [],
    harderVariations: ["Overhead Press"],
    description: "Kneeling position removes lower body compensation. Exposes core stability requirements. High sport transfer for rotational athletes.",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 5. UPPER PULL — HORIZONTAL
  // cluster: pull_horizontal
  // ═══════════════════════════════════════════════════════════════════════════

  {
    name: "Barbell Row",
    movementPattern: "pull_horizontal",
    bodyRegion: "upper_body",
    role: "primary_strength",
    primaryMuscle: "lats",
    secondaryMuscles: ["rhomboids", "rear delts", "biceps", "core"],
    equipment: ["barbell"],
    difficultyLevel: "intermediate",
    neuralDemand: "moderate",
    timeCost: "moderate",
    intentTags: ["strength", "hypertrophy", "athletic"],
    sportTransferTags: ["upper_body_force"],
    jointStressProfile: ["spine_load", "low_back_stress"],
    tags: ["bilateral"],
    clusterId: "pull_horizontal",
    easierVariations: ["Dumbbell Row", "Chest-Supported Row"],
    harderVariations: [],
    description: "Hinge forward, pull bar to lower chest/abdomen. High total body demand. Spine erector fatigue is a limiter — use heavy rows sparingly.",
  },

  {
    name: "Dumbbell Row",
    movementPattern: "pull_horizontal",
    bodyRegion: "upper_body",
    role: "primary_strength",
    unilateral: true,
    primaryMuscle: "lats",
    secondaryMuscles: ["rhomboids", "rear delts", "biceps"],
    equipment: ["dumbbell"],
    difficultyLevel: "beginner",
    neuralDemand: "low",
    timeCost: "low",
    intentTags: ["hypertrophy", "strength"],
    sportTransferTags: ["upper_body_force"],
    jointStressProfile: ["shoulder_dominant"],
    tags: ["unilateral", "beginner_friendly", "time_efficient"],
    clusterId: "pull_horizontal",
    easierVariations: [],
    harderVariations: ["Barbell Row"],
    description: "Supported on bench. Each side works independently. Lower spine load than barbell row. Default swap for most training environments.",
  },

  {
    name: "Chest-Supported Row",
    movementPattern: "pull_horizontal",
    bodyRegion: "upper_body",
    role: "primary_strength",
    primaryMuscle: "lats",
    secondaryMuscles: ["rhomboids", "rear delts", "biceps"],
    equipment: ["dumbbell", "machine"],
    difficultyLevel: "beginner",
    neuralDemand: "low",
    timeCost: "low",
    intentTags: ["hypertrophy", "rehab"],
    sportTransferTags: ["upper_body_force"],
    jointStressProfile: ["shoulder_dominant"],
    tags: ["bilateral", "low_back_sensitive", "beginner_friendly"],
    clusterId: "pull_horizontal",
    easierVariations: [],
    harderVariations: ["Barbell Row", "Dumbbell Row"],
    description: "Chest on incline pad eliminates lower back compensation. Best row option for lower back pain or high fatigue sessions. Pure upper back work.",
  },

  {
    name: "Cable Row",
    movementPattern: "pull_horizontal",
    bodyRegion: "upper_body",
    role: "primary_strength",
    primaryMuscle: "lats",
    secondaryMuscles: ["rhomboids", "rear delts", "biceps"],
    equipment: ["cable"],
    difficultyLevel: "beginner",
    neuralDemand: "low",
    timeCost: "low",
    intentTags: ["hypertrophy", "rehab"],
    sportTransferTags: ["upper_body_force"],
    jointStressProfile: ["shoulder_dominant"],
    tags: ["bilateral", "shoulder_sensitive", "beginner_friendly"],
    clusterId: "pull_horizontal",
    easierVariations: [],
    harderVariations: ["Barbell Row"],
    description: "Seated cable row. Consistent tension throughout ROM. Joint-friendly. Good high-rep option or warm-up. Easy to control load.",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 6. UPPER PULL — VERTICAL
  // cluster: pull_vertical
  // ═══════════════════════════════════════════════════════════════════════════

  {
    name: "Pull-Up",
    movementPattern: "pull_vertical",
    bodyRegion: "upper_body",
    role: "primary_strength",
    primaryMuscle: "lats",
    secondaryMuscles: ["biceps", "rhomboids", "rear delts", "core"],
    equipment: ["bodyweight", "band"],
    difficultyLevel: "intermediate",
    neuralDemand: "moderate",
    timeCost: "low",
    intentTags: ["strength", "hypertrophy", "athletic"],
    sportTransferTags: ["upper_body_force", "trunk_stability"],
    jointStressProfile: ["shoulder_dominant"],
    tags: ["bilateral", "bodyweight_only", "athletic", "time_efficient"],
    clusterId: "pull_vertical",
    easierVariations: ["Assisted Pull-Up", "Lat Pulldown"],
    harderVariations: ["Weighted Pull-Up"],
    description: "Full hang, scaps down and back, chin clears bar. Highest lat demand of any vertical pull. Foundation of upper body relative strength.",
  },

  {
    name: "Weighted Pull-Up",
    movementPattern: "pull_vertical",
    bodyRegion: "upper_body",
    role: "primary_strength",
    primaryMuscle: "lats",
    secondaryMuscles: ["biceps", "rhomboids", "core"],
    equipment: ["bodyweight"],
    difficultyLevel: "advanced",
    neuralDemand: "high",
    timeCost: "low",
    intentTags: ["strength", "athletic"],
    sportTransferTags: ["upper_body_force"],
    jointStressProfile: ["shoulder_dominant"],
    tags: ["bilateral", "athletic"],
    clusterId: "pull_vertical",
    easierVariations: ["Pull-Up"],
    harderVariations: [],
    description: "Belt or vest loaded pull-up. Primary vertical pull strength progression. High relative strength indicator.",
  },

  {
    name: "Lat Pulldown",
    movementPattern: "pull_vertical",
    bodyRegion: "upper_body",
    role: "primary_strength",
    primaryMuscle: "lats",
    secondaryMuscles: ["biceps", "rhomboids"],
    equipment: ["cable", "machine"],
    difficultyLevel: "beginner",
    neuralDemand: "low",
    timeCost: "low",
    intentTags: ["hypertrophy", "strength"],
    sportTransferTags: ["upper_body_force"],
    jointStressProfile: ["shoulder_dominant"],
    tags: ["bilateral", "beginner_friendly"],
    clusterId: "pull_vertical",
    easierVariations: [],
    harderVariations: ["Pull-Up"],
    description: "Machine or cable pulldown. Load is scalable and controlled. Use as regression from pull-ups or for high-rep hypertrophy work.",
  },

  {
    name: "Assisted Pull-Up",
    movementPattern: "pull_vertical",
    bodyRegion: "upper_body",
    role: "primary_strength",
    primaryMuscle: "lats",
    secondaryMuscles: ["biceps", "rhomboids"],
    equipment: ["band", "machine"],
    difficultyLevel: "beginner",
    neuralDemand: "low",
    timeCost: "low",
    intentTags: ["strength", "hypertrophy", "rehab"],
    sportTransferTags: ["upper_body_force"],
    jointStressProfile: ["shoulder_dominant"],
    tags: ["bilateral", "beginner_friendly"],
    clusterId: "pull_vertical",
    easierVariations: ["Lat Pulldown"],
    harderVariations: ["Pull-Up"],
    description: "Band or machine assistance reduces bodyweight demand. Primary regression for athletes who cannot complete full pull-ups.",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 7. POWER / EXPLOSIVE
  // cluster: power_lower | power_upper | power_olympic
  // ═══════════════════════════════════════════════════════════════════════════

  {
    name: "Vertical Jump",
    movementPattern: "power_explosive",
    bodyRegion: "lower_body",
    role: "primary_power",
    primaryMuscle: "quads",
    secondaryMuscles: ["glutes", "hamstrings", "calves"],
    equipment: ["bodyweight"],
    difficultyLevel: "beginner",
    neuralDemand: "high",
    timeCost: "low",
    intentTags: ["power", "athletic", "sport_performance"],
    sportTransferTags: ["lower_body_force", "stiffness", "landing_control"],
    jointStressProfile: ["knee_dominant", "ankle_stress"],
    tags: ["bilateral", "bodyweight_only", "high_impact", "athletic"],
    clusterId: "power_lower",
    easierVariations: [],
    harderVariations: ["Depth Jump", "Loaded Jump Squat"],
    description: "Countermovement to maximum height. Arm swing allowed. Assess and train vertical force production. Landing mechanics are critical.",
  },

  {
    name: "Broad Jump",
    movementPattern: "power_explosive",
    bodyRegion: "lower_body",
    role: "primary_power",
    primaryMuscle: "glutes",
    secondaryMuscles: ["quads", "hamstrings", "calves"],
    equipment: ["bodyweight"],
    difficultyLevel: "beginner",
    neuralDemand: "high",
    timeCost: "low",
    intentTags: ["power", "athletic", "sport_performance"],
    sportTransferTags: ["acceleration", "lower_body_force", "stiffness"],
    jointStressProfile: ["knee_dominant", "ankle_stress", "hip_dominant"],
    tags: ["bilateral", "bodyweight_only", "high_impact", "athletic"],
    clusterId: "power_lower",
    easierVariations: [],
    harderVariations: ["Depth Jump"],
    description: "Horizontal force production from bilateral stance. High acceleration transfer. Deceleration and landing mechanics must be trained alongside.",
  },

  {
    name: "Lateral Bound",
    movementPattern: "power_explosive",
    bodyRegion: "lower_body",
    role: "primary_power",
    unilateral: true,
    primaryMuscle: "glutes",
    secondaryMuscles: ["quads", "adductors", "calves"],
    equipment: ["bodyweight"],
    difficultyLevel: "intermediate",
    neuralDemand: "high",
    timeCost: "low",
    intentTags: ["power", "athletic", "sport_performance"],
    sportTransferTags: ["change_of_direction", "lower_body_force", "stiffness"],
    jointStressProfile: ["knee_dominant", "ankle_stress"],
    tags: ["unilateral", "high_impact", "athletic", "bodyweight_only"],
    clusterId: "power_lower",
    easierVariations: ["Lateral Lunge"],
    harderVariations: ["Alternating Bounds"],
    description: "Push off one leg laterally, stick the landing on the other. Frontal-plane power. High transfer to COD sports.",
  },

  {
    name: "Alternating Bounds",
    movementPattern: "power_explosive",
    bodyRegion: "lower_body",
    role: "primary_power",
    unilateral: true,
    primaryMuscle: "glutes",
    secondaryMuscles: ["quads", "hamstrings", "calves"],
    equipment: ["bodyweight"],
    difficultyLevel: "intermediate",
    neuralDemand: "high",
    timeCost: "low",
    intentTags: ["power", "athletic", "sport_performance"],
    sportTransferTags: ["acceleration", "stiffness", "change_of_direction"],
    jointStressProfile: ["knee_dominant", "ankle_stress"],
    tags: ["unilateral", "high_impact", "athletic", "bodyweight_only"],
    clusterId: "power_lower",
    easierVariations: ["Broad Jump"],
    harderVariations: ["Depth Jump"],
    description: "Exaggerated running stride for max horizontal distance. Stiffness and single-leg power. High sprint and acceleration transfer.",
  },

  {
    name: "Depth Jump",
    movementPattern: "power_explosive",
    bodyRegion: "lower_body",
    role: "primary_power",
    primaryMuscle: "quads",
    secondaryMuscles: ["glutes", "hamstrings", "calves"],
    equipment: ["bodyweight"],
    difficultyLevel: "advanced",
    neuralDemand: "high",
    timeCost: "moderate",
    intentTags: ["power", "sport_performance"],
    sportTransferTags: ["stiffness", "landing_control", "lower_body_force"],
    jointStressProfile: ["knee_dominant", "ankle_stress", "hip_dominant"],
    tags: ["bilateral", "high_impact", "athletic"],
    clusterId: "power_lower",
    easierVariations: ["Vertical Jump", "Broad Jump"],
    harderVariations: [],
    description: "Step off box, land and immediately jump. Shortest ground contact possible. Maximum reactive strength and stiffness training. Use sparingly — very high nervous system cost.",
  },

  {
    name: "Med Ball Slam",
    movementPattern: "power_explosive",
    bodyRegion: "full_body",
    role: "primary_power",
    primaryMuscle: "core",
    secondaryMuscles: ["lats", "shoulders", "glutes"],
    equipment: ["med_ball"],
    difficultyLevel: "beginner",
    neuralDemand: "moderate",
    timeCost: "low",
    intentTags: ["power", "athletic", "fat_loss", "sport_performance"],
    sportTransferTags: ["rotational_power", "trunk_stability"],
    jointStressProfile: ["spine_load"],
    tags: ["bilateral", "athletic", "time_efficient"],
    clusterId: "power_upper",
    easierVariations: [],
    harderVariations: ["Med Ball Rotational Throw"],
    description: "Overhead extension to floor slam. Total body force transfer. Low skill, high power output. Excellent between sets or as primer.",
  },

  {
    name: "Med Ball Rotational Throw",
    movementPattern: "power_explosive",
    bodyRegion: "full_body",
    role: "primary_power",
    primaryMuscle: "core",
    secondaryMuscles: ["obliques", "glutes", "chest", "shoulders"],
    equipment: ["med_ball"],
    difficultyLevel: "intermediate",
    neuralDemand: "high",
    timeCost: "low",
    intentTags: ["power", "athletic", "sport_performance"],
    sportTransferTags: ["rotational_power", "trunk_stability", "anti_rotation"],
    jointStressProfile: ["spine_load"],
    tags: ["bilateral", "athletic"],
    clusterId: "power_upper",
    easierVariations: ["Med Ball Slam"],
    harderVariations: [],
    description: "Hip-loaded rotational throw against wall. Highest sport transfer for rotational athletes — baseball, tennis, MMA, lacrosse, golf.",
  },

  {
    name: "Med Ball Chest Pass",
    movementPattern: "power_explosive",
    bodyRegion: "upper_body",
    role: "primary_power",
    primaryMuscle: "chest",
    secondaryMuscles: ["triceps", "anterior deltoid"],
    equipment: ["med_ball"],
    difficultyLevel: "beginner",
    neuralDemand: "moderate",
    timeCost: "low",
    intentTags: ["power", "athletic"],
    sportTransferTags: ["upper_body_force"],
    jointStressProfile: ["shoulder_dominant"],
    tags: ["bilateral", "time_efficient", "athletic"],
    clusterId: "power_upper",
    easierVariations: [],
    harderVariations: ["Med Ball Rotational Throw"],
    description: "Explosive horizontal push power. Trains horizontal force expression rapidly. Superset with bench press variants for PAP effect.",
  },

  {
    name: "Med Ball Overhead Scoop Toss",
    movementPattern: "power_explosive",
    bodyRegion: "full_body",
    role: "primary_power",
    primaryMuscle: "glutes",
    secondaryMuscles: ["hamstrings", "core", "shoulders"],
    equipment: ["med_ball"],
    difficultyLevel: "beginner",
    neuralDemand: "moderate",
    timeCost: "low",
    intentTags: ["power", "athletic", "sport_performance"],
    sportTransferTags: ["lower_body_force", "stiffness"],
    jointStressProfile: ["spine_load", "hip_dominant"],
    tags: ["bilateral", "athletic", "time_efficient"],
    clusterId: "power_upper",
    easierVariations: [],
    harderVariations: ["Hang Power Clean"],
    description: "Hip hinge into explosive hip extension, ball released overhead backward. Triple extension pattern without Olympic lifting skill requirement.",
  },

  {
    name: "Hang Power Clean",
    movementPattern: "power_explosive",
    bodyRegion: "full_body",
    role: "primary_power",
    primaryMuscle: "glutes",
    secondaryMuscles: ["hamstrings", "traps", "core", "shoulders"],
    equipment: ["barbell"],
    difficultyLevel: "advanced",
    neuralDemand: "high",
    timeCost: "high",
    intentTags: ["power", "strength", "athletic", "sport_performance"],
    sportTransferTags: ["lower_body_force", "acceleration", "stiffness"],
    jointStressProfile: ["spine_load", "wrist_stress"],
    tags: ["bilateral", "athletic"],
    clusterId: "power_olympic",
    easierVariations: ["Med Ball Overhead Scoop Toss", "Hang High Pull"],
    harderVariations: [],
    description: "Barbell from hang position to front rack. Triple extension + catch. Maximum power output. Requires coaching to perform safely.",
  },

  {
    name: "Hang High Pull",
    movementPattern: "power_explosive",
    bodyRegion: "full_body",
    role: "primary_power",
    primaryMuscle: "glutes",
    secondaryMuscles: ["hamstrings", "traps", "core"],
    equipment: ["barbell", "dumbbell", "kettlebell"],
    difficultyLevel: "intermediate",
    neuralDemand: "high",
    timeCost: "moderate",
    intentTags: ["power", "athletic", "sport_performance"],
    sportTransferTags: ["lower_body_force", "acceleration", "stiffness"],
    jointStressProfile: ["spine_load"],
    tags: ["bilateral", "athletic"],
    clusterId: "power_olympic",
    easierVariations: ["Med Ball Overhead Scoop Toss"],
    harderVariations: ["Hang Power Clean"],
    description: "Olympic lift without the catch. All the power stimulus, less technical demand. Bridge between med ball work and full Olympic lifts.",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 8. CORE / TRUNK
  // cluster: core_anti_ext | core_anti_rot | core_rotation | core_lateral
  // ═══════════════════════════════════════════════════════════════════════════

  {
    name: "RKC Plank",
    movementPattern: "core_anti_extension",
    bodyRegion: "core",
    role: "primary_strength",
    primaryMuscle: "core",
    secondaryMuscles: ["glutes", "quads", "shoulders"],
    equipment: ["bodyweight"],
    difficultyLevel: "intermediate",
    neuralDemand: "moderate",
    timeCost: "low",
    intentTags: ["strength", "athletic"],
    sportTransferTags: ["trunk_stability"],
    jointStressProfile: [],
    tags: ["bilateral", "bodyweight_only", "time_efficient"],
    clusterId: "core_anti_ext",
    easierVariations: ["Standard Plank"],
    harderVariations: ["Hollow Hold"],
    description: "Squeeze every muscle. Posterior pelvic tilt, glutes locked, legs driving back. Isometric but brutally demanding. Far superior to passive plank.",
  },

  {
    name: "Hollow Hold",
    movementPattern: "core_anti_extension",
    bodyRegion: "core",
    role: "primary_strength",
    primaryMuscle: "core",
    secondaryMuscles: ["hip flexors", "quads"],
    equipment: ["bodyweight"],
    difficultyLevel: "intermediate",
    neuralDemand: "moderate",
    timeCost: "low",
    intentTags: ["strength", "athletic"],
    sportTransferTags: ["trunk_stability"],
    jointStressProfile: [],
    tags: ["bilateral", "bodyweight_only", "time_efficient"],
    clusterId: "core_anti_ext",
    easierVariations: ["RKC Plank"],
    harderVariations: [],
    description: "Supine: arms overhead, legs extended, lower back pressed to floor. Ribcage down. Sustained full-body anti-extension. Core of gymnastics conditioning.",
  },

  {
    name: "Pallof Press",
    movementPattern: "core_anti_rotation",
    bodyRegion: "core",
    role: "primary_strength",
    primaryMuscle: "core",
    secondaryMuscles: ["obliques", "glutes"],
    equipment: ["cable", "band"],
    difficultyLevel: "beginner",
    neuralDemand: "low",
    timeCost: "low",
    intentTags: ["strength", "athletic", "rehab"],
    sportTransferTags: ["anti_rotation", "trunk_stability"],
    jointStressProfile: [],
    tags: ["bilateral", "beginner_friendly", "shoulder_sensitive"],
    clusterId: "core_anti_rot",
    easierVariations: [],
    harderVariations: ["Half-Kneeling Pallof Press", "Pallof Press with Rotation"],
    description: "Press cable out and return. Resist rotation the whole time. Most underutilized core exercise in athletic training. Essential for rotational sport athletes.",
  },

  {
    name: "Half-Kneeling Pallof Press",
    movementPattern: "core_anti_rotation",
    bodyRegion: "core",
    role: "primary_strength",
    unilateral: true,
    primaryMuscle: "core",
    secondaryMuscles: ["obliques", "glutes", "hip flexors"],
    equipment: ["cable", "band"],
    difficultyLevel: "intermediate",
    neuralDemand: "moderate",
    timeCost: "low",
    intentTags: ["strength", "athletic", "rehab"],
    sportTransferTags: ["anti_rotation", "trunk_stability"],
    jointStressProfile: [],
    tags: ["unilateral", "athletic", "beginner_friendly"],
    clusterId: "core_anti_rot",
    easierVariations: ["Pallof Press"],
    harderVariations: [],
    description: "Kneeling removes lower extremity compensation — pure trunk anti-rotation and hip stability. High sport transfer.",
  },

  {
    name: "Landmine Rotation",
    movementPattern: "core_rotation",
    bodyRegion: "core",
    role: "primary_strength",
    primaryMuscle: "obliques",
    secondaryMuscles: ["core", "shoulders", "glutes"],
    equipment: ["barbell"],
    difficultyLevel: "intermediate",
    neuralDemand: "moderate",
    timeCost: "moderate",
    intentTags: ["strength", "athletic", "sport_performance"],
    sportTransferTags: ["rotational_power", "trunk_stability"],
    jointStressProfile: ["spine_load", "shoulder_dominant"],
    tags: ["bilateral", "athletic"],
    clusterId: "core_rotation",
    easierVariations: ["Pallof Press"],
    harderVariations: ["Med Ball Rotational Throw"],
    description: "Arc the landmine end across the body with hip rotation driving movement. Loaded rotational strength. High transfer for throwing and striking sports.",
  },

  {
    name: "Half-Kneeling Cable Chop",
    movementPattern: "core_rotation",
    bodyRegion: "core",
    role: "primary_strength",
    unilateral: true,
    primaryMuscle: "obliques",
    secondaryMuscles: ["core", "shoulders", "lats"],
    equipment: ["cable", "band"],
    difficultyLevel: "intermediate",
    neuralDemand: "moderate",
    timeCost: "moderate",
    intentTags: ["strength", "athletic", "rehab"],
    sportTransferTags: ["rotational_power", "anti_rotation", "trunk_stability"],
    jointStressProfile: [],
    tags: ["unilateral", "athletic"],
    clusterId: "core_rotation",
    easierVariations: ["Pallof Press"],
    harderVariations: ["Landmine Rotation"],
    description: "High-to-low cable pull in half-kneeling. Diagonal trunk pattern. Integrates hip stability with rotational strength.",
  },

  {
    name: "Side Plank",
    movementPattern: "core_lateral",
    bodyRegion: "core",
    role: "primary_strength",
    primaryMuscle: "obliques",
    secondaryMuscles: ["glutes", "hip abductors"],
    equipment: ["bodyweight"],
    difficultyLevel: "beginner",
    neuralDemand: "low",
    timeCost: "low",
    intentTags: ["strength", "rehab", "athletic"],
    sportTransferTags: ["trunk_stability", "anti_rotation"],
    jointStressProfile: [],
    tags: ["bilateral", "bodyweight_only", "beginner_friendly", "time_efficient"],
    clusterId: "core_lateral",
    easierVariations: [],
    harderVariations: ["Side Plank with Hip Abduction"],
    description: "Hip stacked, no sag. Straight line from head to feet. Most basic lateral stability training. Critical for lumbar-pelvic-hip chain integrity.",
  },

  {
    name: "Side Plank with Hip Abduction",
    movementPattern: "core_lateral",
    bodyRegion: "core",
    role: "primary_strength",
    primaryMuscle: "obliques",
    secondaryMuscles: ["glutes", "hip abductors", "IT band"],
    equipment: ["bodyweight"],
    difficultyLevel: "intermediate",
    neuralDemand: "moderate",
    timeCost: "low",
    intentTags: ["strength", "rehab", "athletic"],
    sportTransferTags: ["trunk_stability"],
    jointStressProfile: [],
    tags: ["bilateral", "bodyweight_only"],
    clusterId: "core_lateral",
    easierVariations: ["Side Plank"],
    harderVariations: [],
    description: "Side plank with top leg raising to hip abduction. Adds glute med demand to lateral trunk stability. Excellent for hip injury prevention.",
  },

  {
    name: "Stir-the-Pot",
    movementPattern: "core_anti_extension",
    bodyRegion: "core",
    role: "primary_strength",
    primaryMuscle: "core",
    secondaryMuscles: ["shoulders", "glutes"],
    equipment: ["bodyweight"],
    difficultyLevel: "advanced",
    neuralDemand: "moderate",
    timeCost: "moderate",
    intentTags: ["strength", "athletic"],
    sportTransferTags: ["trunk_stability"],
    jointStressProfile: ["shoulder_dominant"],
    tags: ["bilateral"],
    clusterId: "core_anti_ext",
    easierVariations: ["RKC Plank"],
    harderVariations: [],
    description: "Forearms on stability ball, small circles while maintaining plank. Simultaneous anti-extension, anti-rotation, and anti-lateral flexion. McGill approved.",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 9. ACCESSORY — LOWER (low priority, removable when time-constrained)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    name: "Leg Curl",
    movementPattern: "accessory_lower",
    bodyRegion: "lower_body",
    role: "accessory",
    primaryMuscle: "hamstrings",
    secondaryMuscles: [],
    equipment: ["machine"],
    difficultyLevel: "beginner",
    neuralDemand: "low",
    timeCost: "low",
    intentTags: ["hypertrophy", "rehab"],
    sportTransferTags: [],
    jointStressProfile: [],
    tags: ["bilateral", "low_priority", "removable_when_compressed"],
    clusterId: undefined,
    easierVariations: [],
    harderVariations: [],
    description: "Isolated hamstring curl. Low systemic fatigue. Use to supplement hinge pattern or for hamstring hypertrophy focus. First to cut when time is short.",
  },

  {
    name: "Leg Extension",
    movementPattern: "accessory_lower",
    bodyRegion: "lower_body",
    role: "accessory",
    primaryMuscle: "quads",
    secondaryMuscles: [],
    equipment: ["machine"],
    difficultyLevel: "beginner",
    neuralDemand: "low",
    timeCost: "low",
    intentTags: ["hypertrophy", "rehab"],
    sportTransferTags: [],
    jointStressProfile: ["knee_dominant"],
    tags: ["bilateral", "low_priority", "removable_when_compressed"],
    clusterId: undefined,
    easierVariations: [],
    harderVariations: [],
    description: "Isolated quad extension. Useful for VMO rehab or hypertrophy supplementation. Remove first when session is compressed.",
  },

  {
    name: "Calf Raise",
    movementPattern: "accessory_lower",
    bodyRegion: "lower_body",
    role: "accessory",
    primaryMuscle: "calves",
    secondaryMuscles: [],
    equipment: ["machine", "dumbbell", "bodyweight"],
    difficultyLevel: "beginner",
    neuralDemand: "low",
    timeCost: "low",
    intentTags: ["hypertrophy"],
    sportTransferTags: ["stiffness"],
    jointStressProfile: ["ankle_stress"],
    tags: ["bilateral", "low_priority", "removable_when_compressed"],
    clusterId: undefined,
    easierVariations: [],
    harderVariations: [],
    description: "Isolated plantar flexion. Important for ankle stiffness in jumping athletes. Otherwise low priority. Slow tempo for hypertrophy.",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 10. ACCESSORY — UPPER (low priority, removable when time-constrained)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    name: "Lateral Raise",
    movementPattern: "accessory_upper",
    bodyRegion: "upper_body",
    role: "accessory",
    primaryMuscle: "lateral deltoid",
    secondaryMuscles: [],
    equipment: ["dumbbell", "cable", "band"],
    difficultyLevel: "beginner",
    neuralDemand: "low",
    timeCost: "low",
    intentTags: ["hypertrophy"],
    sportTransferTags: [],
    jointStressProfile: ["shoulder_dominant"],
    tags: ["bilateral", "low_priority", "removable_when_compressed"],
    clusterId: undefined,
    easierVariations: [],
    harderVariations: [],
    description: "Medial deltoid isolation. Aesthetic focus. Remove first when time-compressed. Pair with rows or as a superset finisher.",
  },

  {
    name: "Triceps Pushdown",
    movementPattern: "accessory_upper",
    bodyRegion: "upper_body",
    role: "accessory",
    primaryMuscle: "triceps",
    secondaryMuscles: [],
    equipment: ["cable", "band"],
    difficultyLevel: "beginner",
    neuralDemand: "low",
    timeCost: "low",
    intentTags: ["hypertrophy"],
    sportTransferTags: [],
    jointStressProfile: [],
    tags: ["bilateral", "low_priority", "removable_when_compressed"],
    clusterId: undefined,
    easierVariations: [],
    harderVariations: [],
    description: "Isolated triceps extension via cable or band. Low systemic fatigue. High-rep finishing work. Remove during time-compressed sessions.",
  },

  {
    name: "Biceps Curl",
    movementPattern: "accessory_upper",
    bodyRegion: "upper_body",
    role: "accessory",
    primaryMuscle: "biceps",
    secondaryMuscles: [],
    equipment: ["dumbbell", "barbell", "cable", "band"],
    difficultyLevel: "beginner",
    neuralDemand: "low",
    timeCost: "low",
    intentTags: ["hypertrophy"],
    sportTransferTags: [],
    jointStressProfile: ["elbow_stress"],
    tags: ["bilateral", "low_priority", "removable_when_compressed"],
    clusterId: undefined,
    easierVariations: [],
    harderVariations: [],
    description: "Isolated elbow flexion. Low systemic fatigue. Hypertrophy accessory. Last exercise to include, first to remove. Supinate at peak for full contraction.",
  },

  {
    name: "Face Pull",
    movementPattern: "accessory_upper",
    bodyRegion: "upper_body",
    role: "accessory",
    primaryMuscle: "rear delts",
    secondaryMuscles: ["rotator cuff", "rhomboids", "traps"],
    equipment: ["cable", "band"],
    difficultyLevel: "beginner",
    neuralDemand: "low",
    timeCost: "low",
    intentTags: ["rehab", "hypertrophy"],
    sportTransferTags: [],
    jointStressProfile: ["shoulder_dominant"],
    tags: ["bilateral", "shoulder_sensitive", "beginner_friendly", "removable_when_compressed"],
    clusterId: undefined,
    easierVariations: [],
    harderVariations: [],
    description: "Cable pull to face with external rotation. Rear delt and rotator cuff health. Essential in high-pressing programs. Pairs well between pressing sets.",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 11. CONDITIONING / WORK CAPACITY
  // ═══════════════════════════════════════════════════════════════════════════

  {
    name: "Sled Push",
    movementPattern: "conditioning",
    bodyRegion: "full_body",
    role: "conditioning",
    primaryMuscle: "quads",
    secondaryMuscles: ["glutes", "core", "shoulders"],
    equipment: ["sled"],
    difficultyLevel: "beginner",
    neuralDemand: "low",
    timeCost: "moderate",
    intentTags: ["endurance", "athletic", "fat_loss", "sport_performance"],
    sportTransferTags: ["acceleration", "lower_body_force"],
    jointStressProfile: [],
    tags: ["bilateral", "low_impact", "athletic"],
    clusterId: "conditioning_work_capacity",
    easierVariations: [],
    harderVariations: [],
    description: "No eccentric load — virtually zero DOMS. High cardiac and metabolic output. Excellent for conditioning in any training phase without compromising recovery.",
  },

  {
    name: "Assault Bike Sprint",
    movementPattern: "conditioning",
    bodyRegion: "full_body",
    role: "conditioning",
    primaryMuscle: "quads",
    secondaryMuscles: ["glutes", "hamstrings", "shoulders", "core"],
    equipment: ["machine"],
    difficultyLevel: "beginner",
    neuralDemand: "low",
    timeCost: "low",
    intentTags: ["endurance", "fat_loss", "sport_performance"],
    sportTransferTags: ["lower_body_force"],
    jointStressProfile: [],
    tags: ["bilateral", "low_impact", "time_efficient"],
    clusterId: "conditioning_work_capacity",
    easierVariations: [],
    harderVariations: [],
    description: "Air resistance = infinite scalability. Sprint intervals for maximum metabolic demand. Low joint stress. Best machine conditioning option available.",
  },

  {
    name: "Tempo Run",
    movementPattern: "conditioning",
    bodyRegion: "full_body",
    role: "conditioning",
    primaryMuscle: "quads",
    secondaryMuscles: ["glutes", "hamstrings", "calves", "core"],
    equipment: ["bodyweight"],
    difficultyLevel: "intermediate",
    neuralDemand: "moderate",
    timeCost: "high",
    intentTags: ["endurance", "sport_performance"],
    sportTransferTags: ["acceleration", "stiffness"],
    jointStressProfile: ["ankle_stress", "knee_dominant"],
    tags: ["high_impact", "athletic", "outdoor"],
    clusterId: "conditioning_work_capacity",
    easierVariations: [],
    harderVariations: ["Shuttle Run"],
    description: "Submaximal runs at 70-80% effort. Aerobic base and work capacity. High sport transfer for field and court sport athletes. Monitor total weekly volume.",
  },

  {
    name: "Shuttle Run",
    movementPattern: "conditioning",
    bodyRegion: "full_body",
    role: "conditioning",
    primaryMuscle: "quads",
    secondaryMuscles: ["glutes", "hamstrings", "calves"],
    equipment: ["bodyweight"],
    difficultyLevel: "intermediate",
    neuralDemand: "high",
    timeCost: "moderate",
    intentTags: ["endurance", "sport_performance", "athletic"],
    sportTransferTags: ["change_of_direction", "acceleration", "deceleration"],
    jointStressProfile: ["knee_dominant", "ankle_stress"],
    tags: ["high_impact", "athletic"],
    clusterId: "conditioning_work_capacity",
    easierVariations: ["Tempo Run"],
    harderVariations: [],
    description: "Short distance COD runs. Trains deceleration, re-acceleration, and metabolic capacity simultaneously. Essential for team sport athletes.",
  },

  {
    name: "Loaded Carry Circuit",
    movementPattern: "conditioning",
    bodyRegion: "full_body",
    role: "conditioning",
    primaryMuscle: "core",
    secondaryMuscles: ["traps", "shoulders", "glutes", "forearms"],
    equipment: ["dumbbell", "kettlebell", "barbell"],
    difficultyLevel: "beginner",
    neuralDemand: "low",
    timeCost: "moderate",
    intentTags: ["endurance", "strength", "athletic"],
    sportTransferTags: ["trunk_stability", "lower_body_force"],
    jointStressProfile: ["spine_load"],
    tags: ["bilateral", "time_efficient", "athletic"],
    clusterId: "conditioning_work_capacity",
    easierVariations: [],
    harderVariations: [],
    description: "Farmer carry, suitcase carry, or overhead carry. Builds grip, trunk stiffness, and gait-pattern conditioning. High value, low technical complexity.",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 12. MOBILITY / PREP / ACTIVATION
  // ═══════════════════════════════════════════════════════════════════════════

  {
    name: "Ankle Pogo Series",
    movementPattern: "mobility_prep",
    bodyRegion: "lower_body",
    role: "prep_activation",
    primaryMuscle: "calves",
    secondaryMuscles: ["plantar fascia", "achilles"],
    equipment: ["bodyweight"],
    difficultyLevel: "beginner",
    neuralDemand: "low",
    timeCost: "low",
    intentTags: ["activation", "mobility", "sport_performance"],
    sportTransferTags: ["stiffness"],
    jointStressProfile: ["ankle_stress"],
    tags: ["bilateral", "bodyweight_only", "warm_up", "time_efficient"],
    clusterId: undefined,
    easierVariations: [],
    harderVariations: [],
    description: "Rapid bilateral ankle hops, minimal knee bend. Pre-activates SSC in Achilles and plantar fascia. Must-have before sprint, jump, or agility work.",
  },

  {
    name: "Hip 90/90 Mobility Drill",
    movementPattern: "mobility_prep",
    bodyRegion: "lower_body",
    role: "prep_activation",
    primaryMuscle: "hip external rotators",
    secondaryMuscles: ["hip flexors", "adductors"],
    equipment: ["bodyweight"],
    difficultyLevel: "beginner",
    neuralDemand: "low",
    timeCost: "low",
    intentTags: ["mobility", "activation", "rehab"],
    sportTransferTags: ["change_of_direction"],
    jointStressProfile: [],
    tags: ["bilateral", "bodyweight_only", "warm_up", "time_efficient"],
    clusterId: undefined,
    easierVariations: [],
    harderVariations: [],
    description: "Seated or supine 90/90 hip internal and external rotation. Prepares hip range of motion before heavy lower body work. Key for athletes with sitting lifestyles.",
  },

  {
    name: "Glute Activation Circuit",
    movementPattern: "mobility_prep",
    bodyRegion: "lower_body",
    role: "prep_activation",
    primaryMuscle: "glutes",
    secondaryMuscles: ["hip abductors"],
    equipment: ["band", "bodyweight"],
    difficultyLevel: "beginner",
    neuralDemand: "low",
    timeCost: "low",
    intentTags: ["activation", "rehab"],
    sportTransferTags: ["lower_body_force"],
    jointStressProfile: [],
    tags: ["bilateral", "bodyweight_only", "warm_up", "time_efficient", "removable_when_compressed"],
    clusterId: undefined,
    easierVariations: [],
    harderVariations: [],
    description: "Clamshells, lateral band walks, and glute bridges in sequence. Pre-activates posterior chain before squats, hinges, and sprint work. 5 minutes max.",
  },

  {
    name: "Trunk Brace Prep",
    movementPattern: "mobility_prep",
    bodyRegion: "core",
    role: "prep_activation",
    primaryMuscle: "core",
    secondaryMuscles: ["diaphragm", "pelvic floor"],
    equipment: ["bodyweight"],
    difficultyLevel: "beginner",
    neuralDemand: "low",
    timeCost: "low",
    intentTags: ["activation", "rehab", "athletic"],
    sportTransferTags: ["trunk_stability"],
    jointStressProfile: [],
    tags: ["bilateral", "bodyweight_only", "warm_up", "time_efficient"],
    clusterId: undefined,
    easierVariations: [],
    harderVariations: [],
    description: "Breathing-based IAP work and brace cuing. Teaches true 360-degree core engagement. Essential before heavy compound lifts. 3-5 deep breath reps.",
  },

  {
    name: "Scapular Positioning Drills",
    movementPattern: "mobility_prep",
    bodyRegion: "upper_body",
    role: "prep_activation",
    primaryMuscle: "scapular stabilizers",
    secondaryMuscles: ["rotator cuff", "lower traps", "serratus"],
    equipment: ["band", "bodyweight"],
    difficultyLevel: "beginner",
    neuralDemand: "low",
    timeCost: "low",
    intentTags: ["activation", "rehab"],
    sportTransferTags: [],
    jointStressProfile: ["shoulder_dominant"],
    tags: ["bilateral", "bodyweight_only", "warm_up", "time_efficient", "shoulder_sensitive"],
    clusterId: undefined,
    easierVariations: [],
    harderVariations: [],
    description: "Band pull-aparts, prone Y/T/W, or wall slides. Sets shoulder girdle before pressing and pulling work. Reduces injury risk in high-volume upper sessions.",
  },

  {
    name: "Dynamic Warm-Up Sprint Prep",
    movementPattern: "mobility_prep",
    bodyRegion: "full_body",
    role: "prep_activation",
    primaryMuscle: "hip flexors",
    secondaryMuscles: ["hamstrings", "calves", "glutes"],
    equipment: ["bodyweight"],
    difficultyLevel: "beginner",
    neuralDemand: "moderate",
    timeCost: "moderate",
    intentTags: ["activation", "athletic", "mobility"],
    sportTransferTags: ["acceleration", "stiffness"],
    jointStressProfile: [],
    tags: ["bilateral", "bodyweight_only", "warm_up", "athletic"],
    clusterId: undefined,
    easierVariations: [],
    harderVariations: [],
    description: "Skips, high knees, A-march, leg swings, and short sprint build-ups. Full neuromuscular prep for speed and power sessions. Cannot be skipped before sprint work.",
  },
];

// ─── Seed Runner ──────────────────────────────────────────────────────────────

async function main() {
  console.log("Deactivating all existing exercises (replacing with decision-ready library)...");
  await db.update(exerciseLibrary).set({ isActive: false });
  console.log("All existing exercises deactivated.");

  console.log(`\nSeeding ${EXERCISES.length} decision-ready exercises...`);

  let inserted = 0;
  let updated = 0;

  for (const ex of EXERCISES) {
    const result = await db
      .insert(exerciseLibrary)
      .values({
        name: ex.name,
        movementPattern: ex.movementPattern,
        bodyRegion: ex.bodyRegion,
        role: ex.role,
        unilateral: ex.unilateral ?? false,
        primaryMuscle: ex.primaryMuscle,
        secondaryMuscles: ex.secondaryMuscles,
        equipment: ex.equipment,
        difficultyLevel: ex.difficultyLevel,
        neuralDemand: ex.neuralDemand ?? "moderate",
        timeCost: ex.timeCost ?? "moderate",
        intentTags: ex.intentTags,
        sportTransferTags: ex.sportTransferTags ?? [],
        jointStressProfile: ex.jointStressProfile,
        tags: ex.tags ?? [],
        clusterId: ex.clusterId,
        easierVariations: ex.easierVariations,
        harderVariations: ex.harderVariations,
        description: ex.description,
        isActive: true,
      })
      .onConflictDoUpdate({
        target: exerciseLibrary.name,
        set: {
          movementPattern: sql`excluded.movement_pattern`,
          bodyRegion: sql`excluded.body_region`,
          role: sql`excluded.role`,
          unilateral: sql`excluded.unilateral`,
          primaryMuscle: sql`excluded.primary_muscle`,
          secondaryMuscles: sql`excluded.secondary_muscles`,
          equipment: sql`excluded.equipment`,
          difficultyLevel: sql`excluded.difficulty_level`,
          neuralDemand: sql`excluded.neural_demand`,
          timeCost: sql`excluded.time_cost`,
          intentTags: sql`excluded.intent_tags`,
          sportTransferTags: sql`excluded.sport_transfer_tags`,
          jointStressProfile: sql`excluded.joint_stress_profile`,
          tags: sql`excluded.tags`,
          clusterId: sql`excluded.cluster_id`,
          easierVariations: sql`excluded.easier_variations`,
          harderVariations: sql`excluded.harder_variations`,
          description: sql`excluded.description`,
          isActive: sql`excluded.is_active`,
        },
      })
      .returning({ id: exerciseLibrary.id });

    if (result.length > 0) {
      inserted++;
    } else {
      updated++;
    }
  }

  console.log(`Done. ${inserted} exercises seeded (${updated} updated if already existed).`);

  // Print summary by movement pattern
  const byPattern: Record<string, number> = {};
  for (const ex of EXERCISES) {
    byPattern[ex.movementPattern] = (byPattern[ex.movementPattern] ?? 0) + 1;
  }
  console.log("\nMovement Bucket Summary:");
  for (const [pattern, count] of Object.entries(byPattern).sort()) {
    console.log(`  ${pattern.padEnd(25)} ${count} exercises`);
  }

  process.exit(0);
}

main().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
